import{a as P,i as u,S as q}from"./assets/vendor-C9vNCoLC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const E="50348932-e8606ea56be3b9c13822f278e",M="https://pixabay.com/api/";async function m(t,e){try{const s=await P.get(M,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:e}});return s.data.hits.length===0&&u.show({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter",class:"custom-toast",iconUrl:"../img/izi.svg"}),s.data}catch(s){throw u.show({title:"Error",message:"Something went wrong!",position:"bottomCenter",class:"custom-toast"}),s}}const f=document.querySelector(".gallery"),g=document.querySelector(".loader");let $=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function U(){f.innerHTML=""}function x(t){const{webformatURL:e,largeImageURL:s,tags:c,likes:o,views:r,comments:n,downloads:v}=t;return`
  
        <li class="gallery-item">
<a class='gallery-link' href="${s}" target='_blank'>
  <img src='${e}' alt="${c}" class="gallery-image">
</a>
<div class='info'>
  <p>Likes: </br><b></b>${o}</b></p>
  <p>Views: </br><b>${r}</b></p>
  <p>Comments: </br><b>${n}</b></p>
  <p>Downloads: </br><b>${v}</b></p>
</div>
</li>

`}function B(t){return t.map(x).join("")}function h(t){const e=B(t);f.insertAdjacentHTML("beforeend",e),$.refresh()}function p(){g.classList.remove("is-hidden")}function y(){g.classList.add("is-hidden")}const b=document.querySelector(".load-more");function C(){b.classList.remove("hidden")}function d(){b.classList.add("hidden")}function L(t,e){t<e?C():d()}function w(t,e){t===e&&u.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",class:"custom-toast",iconUrl:"../img/izi.svg"})}function O(){const t=document.querySelector(".gallery-item");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}let a=0,l,i=0;const S=15,D=document.querySelector(".form");D.addEventListener("submit",H);async function H(t){if(t.preventDefault(),d(),l=t.target.elements["search-text"].value.trim(),a=1,!!l){p(),U();try{const e=await m(l,a);i=Math.ceil(e.totalHits/S),h(e.hits),L(a,i)}catch{u.show({title:"Error",message:"Something went wrong!",position:"bottomCenter",class:"custom-toast"})}y(),w(a,i),t.target.reset()}}const I=document.querySelector(".load-more");I.addEventListener("click",T);async function T(t){t.preventDefault(),a+=1,d(),p();try{const e=await m(l,a);i=Math.ceil(e.totalHits/S),L(a,i),h(e.hits),O()}catch(e){console.error(e)}w(a,i),y()}
//# sourceMappingURL=index.js.map
