import{a as v,i as d,S as M}from"./assets/vendor-QQhsBNEi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function a(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=a(o);fetch(o.href,r)}})();const q="50348932-e8606ea56be3b9c13822f278e",P="https://pixabay.com/api/";async function m(t,e){try{const a=await v.get(P,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:e}});return a.data.hits.length===0&&d.show({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter",class:"custom-toast",iconUrl:"../img/izi.svg"}),a.data}catch(a){throw d.show({title:"Error",message:"Something went wrong!",position:"bottomCenter",class:"custom-toast"}),a}}const f=document.querySelector(".gallery"),g=document.querySelector(".loader");let E=new M(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function U(){f.innerHTML=""}function $(t){const{webformatURL:e,largeImageURL:a,tags:c,likes:o,views:r,comments:i,downloads:S}=t;return`
  
        <li class="gallery-item">
<a class='gallery-link' href="${a}" target='_blank'>
  <img src='${e}' alt="${c}" class="gallery-image">
</a>
<div class='info'>
  <p>Likes: </br><b></b>${o}</b></p>
  <p>Views: </br><b>${r}</b></p>
  <p>Comments: </br><b>${i}</b></p>
  <p>Downloads: </br><b>${S}</b></p>
</div>
</li>

`}function x(t){return t.map($).join("")}function h(t){const e=x(t);f.insertAdjacentHTML("beforeend",e),E.refresh()}function p(){g.classList.remove("is-hidden")}function y(){g.classList.add("is-hidden")}function B(){document.querySelector(".load-more").classList.remove("hidden")}function u(){document.querySelector(".load-more").classList.add("hidden")}function b(t,e){t<e?B():u()}function L(t,e){t===e&&d.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",class:"custom-toast",iconUrl:"../img/izi.svg"})}function O(){const t=document.querySelector(".gallery-item");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}let s=0,l,n=0;const w=15,C=document.querySelector(".form");C.addEventListener("submit",D);async function D(t){if(t.preventDefault(),u(),l=t.target.elements["search-text"].value.trim(),s=1,!!l){U(),p();try{const e=await m(l,s);n=Math.ceil(e.totalHits/w),h(e.hits),b(s,n)}catch(e){console.error(e)}y(),L(s,n),t.target.reset()}}const H=document.querySelector(".load-more");H.addEventListener("click",I);async function I(t){t.preventDefault(),s+=1,u(),p();try{const e=await m(l,s);n=Math.ceil(e.totalHits/w),b(s,n),h(e.hits),O()}catch(e){console.error(e)}L(s,n),y()}
//# sourceMappingURL=index.js.map
